### Variables
@base = http://192.168.56.6:8080/api

### 1. Inscription -> renvoie accessToken + refreshToken
# @name register
POST {{base}}/auth/register
Content-Type: application/json

{
  "email": "alex@sans-limite.dev",
  "password": "motdepasse123x",
  "username": "alex.martin",
  "name": "Alexandre Martin"
}

### Capture le token de la réponse précédente
@token = {{register.response.body.accessToken}}

### 2. Connexion (si déjà inscrit)
# @name login
POST {{base}}/auth/login
Content-Type: application/json

{ 
  "email": "alexx@sans-limite.dev",
  "password": "motdepasse123x" 
}
### Capture le token de la réponse précédente
@token = {{login.response.body.accessToken}}
### 3. Créer une publication
# @name createPost
POST {{base}}/posts
Authorization: Bearer {{token}}
Content-Type: application/json

{ "title": "premier run", "content": "10 km ce matin" }
### Capture le token de la réponse précédente
@postId = {{createPost.response.body.id}}

### 4. Fil d'actualité (public)
GET {{base}}/posts

### 5. Liker
POST {{base}}/posts/{{postId}}/like
Authorization: Bearer {{token}}

### 6. Commenter
POST {{base}}/posts/{{postId}}/comments
Authorization: Bearer {{token}}
Content-Type: application/json

{ "content": "Bravo !" }

### 7. Notifications
GET {{base}}/notifications
Authorization: Bearer {{token}}

### 8. Profil public
GET {{base}}/users/alex.martin
